services:
    postgres:
        image: 'postgres:16.4'
        environment:
            - 'POSTGRES_DB=test'
            - 'POSTGRES_PASSWORD=test'
            - 'POSTGRES_USER=test'
            - 'PGUSER=test'
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
